spec:
  containers:
  - image: cr.yandex/crpi12e49mu5oaajskhn/healthcheck:latest
    securityContext:
      privileged: true
    stdin: true
    tty: true
    
    env:
    
    - name: NODE_DATABASE_URL
      value: postgres://healthcheck:aefac2e2d9fccd1@postgres/postgres
    
    - name: NODE_BIND_ADDRESS
      value: 0.0.0.0:80
    
    